name: MyHolidays

on:
  workflow_dispatch:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Enter Api folder
      run: cd Api
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Enter Tests folder
      run: cd ../Tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  deploy-staging:
    runs-on: ubuntu-22.04
    environment:
      name: staging
      url: 'myholidays-staging.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy staging
  
  deploy-beta:
    runs-on: ubuntu-22.04
    environment:
      name: deploy-staging
      url: 'myholidays-beta.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy beta
  
  deploy-production:
    runs-on: ubuntu-22.04
    environment:
      name: production
      url: 'myholidays.com'
    needs: deploy-beta
    steps:
      - name: Run a one-line script
        run: echo Deploy production
