name: MyHolidays

on:
  workflow_dispatch:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: cd Api && dotnet restore
    - name: Build
      run: cd Api && dotnet build --no-restore
    - name: Test
      run: cd Tests && dotnet test --no-build --verbosity normal
  
  deploy-staging:
    runs-on: ubuntu-22.04
    environment:
      name: staging
      url: 'https://myholidays-staging.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy staging
  
  deploy-beta:
    runs-on: ubuntu-22.04
    environment:
      name: beta
      url: 'https://myholidays-beta.com'
    needs: deploy-staging
    steps:
      - name: Run a one-line script
        run: echo Deploy beta
  
  deploy-production:
    runs-on: ubuntu-22.04
    environment:
      name: production
      url: 'https://my-holidays-api.herokuapp.com/swagger/index.html'
    needs: deploy-beta
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: Login to Heroku Container Registry
        run: cd Api && heroku container:login
      - name: Build and push
        run: cd Api && heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
      - name: Release
        run: cd Api && heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
